/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_pixelworldbridge_free: (a: number, b: number) => void;
export const pixelworldbridge_click: (a: number, b: number, c: number) => any;
export const pixelworldbridge_mount: (a: number, b: any, c: any) => any;
export const pixelworldbridge_new: (a: any, b: any) => number;
export const pixelworldbridge_pointer_down: (a: number, b: number, c: number, d: number) => any;
export const pixelworldbridge_pointer_move: (a: number, b: number, c: number, d: number, e: number) => any;
export const pixelworldbridge_pointer_up: (a: number, b: number) => any;
export const pixelworldbridge_tick: (a: number, b: number) => any;
export const pixelworldbridge_unmount: (a: number) => any;
export const pixelworldbridge_update: (a: number, b: any) => any;
export const pixelworldbridge_wheel: (a: number, b: number) => any;
export const wasm_bindgen__convert__closures_____invoke__h656285ab01c66ca0: (a: number, b: number, c: any) => [number, number];
export const wasm_bindgen__convert__closures_____invoke__h5b8e399d53c6236b: (a: number, b: number, c: any, d: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h1089e505c78a14e4: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h1089e505c78a14e4_3: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h1089e505c78a14e4_4: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h1089e505c78a14e4_5: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h1089e505c78a14e4_6: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h1089e505c78a14e4_7: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h1089e505c78a14e4_8: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h1089e505c78a14e4_9: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h2c6d6c1dfa024e53: (a: number, b: number, c: number) => void;
export const wasm_bindgen__convert__closures_____invoke__h953c336461e674c0: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__ha544621b2880cc31: (a: number, b: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_exn_store: (a: number) => void;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_destroy_closure: (a: number, b: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
