[package]
name = "wasm_build_suite"
version = "0.1.0"
edition = "2024"

[dependencies]
hex = { workspace = true }
oasis7_wasm_build = { path = "../../crates/oasis7_wasm_build" }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
wasm-encoder = { workspace = true }
wasmparser = { workspace = true }
