#!/usr/bin/env python3
"""Focused authority and planning contract for the hosted preview."""

import importlib.util
import hashlib
import os
import shutil
import subprocess
import tempfile
import textwrap
import unittest
from pathlib import Path
from unittest import mock

from projection_publication_contract import build_contract, encode_marker


ROOT = Path(__file__).resolve().parents[2]
DRIVER_PATH = ROOT / "scripts/pm/ci-required-scope-preview.py"
SPEC = importlib.util.spec_from_file_location("required_preview", DRIVER_PATH)
PREVIEW = importlib.util.module_from_spec(SPEC)
SPEC.loader.exec_module(PREVIEW)


class RequiredScopePreviewTests(unittest.TestCase):
    def context(self):
        return {
            "PREVIEW_REPOSITORY": "eng-cc/oasis7",
            "PREVIEW_EVENT_NAME": "workflow_dispatch",
            "PREVIEW_REF": "refs/heads/main",
            "PREVIEW_WORKFLOW_SHA": "a" * 40,
            "PREVIEW_RUN_ATTEMPT": "1",
            "PREVIEW_RUN_ID": "20260925001",
            "PREVIEW_PR_NUMBER": "3992",
            "PREVIEW_TASK_UID": "task_" + "b" * 32,
            "PREVIEW_BASE_SHA": "a" * 40,
            "PREVIEW_HEAD_SHA": "d" * 40,
            "PREVIEW_TESTED_TREE_SHA": "e" * 40,
            "PREVIEW_SCENARIO": "doc_checker_contracts",
        }

    def public_pr_payload(self, context, *, task_uid=None, publication_uid=None):
        task_uid = task_uid or context["PREVIEW_TASK_UID"]
        publication_uid = publication_uid or task_uid
        contract = build_contract(
            task_uid=publication_uid,
            source_head_oid=context["PREVIEW_HEAD_SHA"],
            scope_base_oid=context["PREVIEW_BASE_SHA"],
            projection_digest="sha256:" + "c" * 64,
            revision=3,
            clauses=["{\"id\":\"required-gate-versioned-preview\",\"revision\":\"v1\"}"],
        )
        body = (
            f"Task: {task_uid}\n\nRefs #4016\n\n\n\n"
            "Generated by ./scripts/prepare-task-pr.sh.\n\n"
            + encode_marker(contract)
        )
        return {
            "state": "open",
            "body": body,
            "base": {"ref": "main", "sha": context["PREVIEW_BASE_SHA"],
                     "repo": {"full_name": "eng-cc/oasis7"}},
            "head": {"sha": context["PREVIEW_HEAD_SHA"],
                     "repo": {"full_name": "eng-cc/oasis7"}},
        }

    def test_dispatch_identity_is_canonical_and_complete(self):
        context = PREVIEW.validate_context(self.context())
        self.assertEqual(context["PREVIEW_REPOSITORY"], "eng-cc/oasis7")
        for key in ("PREVIEW_WORKFLOW_SHA", "PREVIEW_BASE_SHA", "PREVIEW_HEAD_SHA", "PREVIEW_TESTED_TREE_SHA"):
            self.assertRegex(context[key], PREVIEW.SHA_RE)

    def test_rejects_noncanonical_ref_repository_uid_and_scenario(self):
        for key, value in (
            ("PREVIEW_REPOSITORY", "attacker/oasis7"),
            ("PREVIEW_REF", "refs/heads/feature"),
            ("PREVIEW_EVENT_NAME", "pull_request"),
            ("PREVIEW_RUN_ATTEMPT", "2"),
            ("PREVIEW_RUN_ID", "0"),
            ("PREVIEW_TASK_UID", "task_invalid"),
            ("PREVIEW_SCENARIO", "full"),
            ("PREVIEW_TESTED_TREE_SHA", "e" * 39),
            ("PREVIEW_BASE_SHA", "c" * 40),
        ):
            candidate = self.context()
            candidate[key] = value
            with self.subTest(key=key), self.assertRaises(SystemExit):
                PREVIEW.validate_context(candidate)

    def test_public_pr_identity_requires_exact_same_repo_open_candidate(self):
        context = self.context()
        payload = self.public_pr_payload(context)
        self.assertIs(PREVIEW.validate_pr_payload(payload, context), payload)
        for change in (
            {"state": "closed"},
            {"body": self.public_pr_payload(
                context, task_uid="task_" + "f" * 32
            )["body"]},
            {"body": self.public_pr_payload(
                context, publication_uid="task_" + "f" * 32
            )["body"]},
            {"body": "\n".join(payload["body"].splitlines()[1:])},
            {"body": payload["body"].split("<!-- oasis7-ci-impact-publication:v2 -->", 1)[0]},
            {"base": {**payload["base"], "ref": "release"}},
            {"base": {**payload["base"], "repo": {"full_name": "other/repo"}}},
            {"head": {**payload["head"], "repo": {"full_name": "contributor/oasis7"}}},
            {"head": {**payload["head"], "sha": "f" * 40}},
        ):
            candidate = {**payload, **change}
            with self.subTest(change=change), self.assertRaises(SystemExit):
                PREVIEW.validate_pr_payload(candidate, context)

    def test_public_pr_identity_accepts_live_canonical_v2_body_shape(self):
        context = self.context()
        context.update({
            "PREVIEW_TASK_UID": "task_1a2856fa0014493896906b9e906f5f26",
            "PREVIEW_BASE_SHA": "aad4952584023cf3c739d0034a7d76036fea733a",
            "PREVIEW_HEAD_SHA": "cb0ed9e96a69b8383c58fc87a54e449eac381c55",
        })
        body = r"""Task: task_1a2856fa0014493896906b9e906f5f26

Refs #4001



Generated by ./scripts/prepare-task-pr.sh.

<!-- oasis7-ci-impact-publication:v2 -->
{"clauses":["{\"id\":\"required-gate-scope-policy\",\"revision\":\"required-domain-split/v1\"}","{\"id\":\"required-gate-versioned-preview\",\"revision\":\"v1\"}"],"contract_digest":"sha256:c65c8cdf66bf0dfe1654c8cf431a2b8c6796632829d0e1a5a92a1097e0eb62b5","projection_digest":"sha256:5ec0706acd029e64d0dd6703d639236eea778082043fa468296e86ddc74cad21","revision":3,"schema":"oasis7-ci-impact-publication/v2","scope_base_oid":"aad4952584023cf3c739d0034a7d76036fea733a","source_head_oid":"cb0ed9e96a69b8383c58fc87a54e449eac381c55","task_uid":"task_1a2856fa0014493896906b9e906f5f26"}"""
        payload = {
            "state": "open",
            "body": body,
            "base": {"ref": "main", "sha": context["PREVIEW_BASE_SHA"],
                     "repo": {"full_name": "eng-cc/oasis7"}},
            "head": {"sha": context["PREVIEW_HEAD_SHA"],
                     "repo": {"full_name": "eng-cc/oasis7"}},
        }
        self.assertEqual(body.count(context["PREVIEW_TASK_UID"]), 2)
        self.assertIs(PREVIEW.validate_pr_payload(payload, context), payload)

    def make_merge_fixture(self, temporary, extra_path=False, wrong_config=False, reverse_parents=False):
        root = Path(temporary)

        def git(*args):
            return subprocess.check_output(["git", "-C", str(root), *args], text=True).strip()

        def run_git(*args):
            subprocess.run(["git", "-C", str(root), *args], check=True, stdout=subprocess.DEVNULL)

        run_git("init", "-q")
        run_git("config", "user.name", "Preview test")
        run_git("config", "user.email", "preview-test@example.invalid")
        fixture_path = root / PREVIEW.FIXTURE
        fixture_path.parent.mkdir(parents=True)
        trusted_fixture = (ROOT / PREVIEW.FIXTURE).read_bytes()
        fixture_path.write_bytes(trusted_fixture)
        effective = root / PREVIEW.EFFECTIVE_CONFIG
        effective.parent.mkdir(parents=True, exist_ok=True)
        effective.write_bytes(b"legacy config\n")
        run_git("add", PREVIEW.FIXTURE, PREVIEW.EFFECTIVE_CONFIG)
        run_git("commit", "-qm", "base")
        base = git("rev-parse", "HEAD")
        effective.write_bytes(b"invalid candidate config\n" if wrong_config else trusted_fixture)
        if extra_path:
            (root / "extra.txt").write_text("unapproved tree change\n")
            run_git("add", "extra.txt")
        run_git("add", PREVIEW.EFFECTIVE_CONFIG)
        run_git("commit", "-qm", "candidate")
        head = git("rev-parse", "HEAD")
        head_tree = git("rev-parse", "HEAD^{tree}")
        if reverse_parents:
            merge = subprocess.check_output(
                ["git", "-C", str(root), "commit-tree", head_tree, "-p", head, "-p", base, "-m", "merge"],
                text=True,
            ).strip()
        else:
            merge = subprocess.check_output(
                ["git", "-C", str(root), "commit-tree", head_tree, "-p", base, "-p", head, "-m", "merge"],
                text=True,
            ).strip()
        tree = git("rev-parse", f"{merge}^{{tree}}")
        return root, base, head, merge, tree

    def test_merge_verifier_rejects_wrong_base_head_tree_parents_and_extra_paths(self):
        with tempfile.TemporaryDirectory() as temporary:
            root, base, head, merge, tree = self.make_merge_fixture(temporary)
            self.assertEqual(PREVIEW.validate_merge_tree(root, base, head, merge, tree), [PREVIEW.EFFECTIVE_CONFIG])
            PREVIEW.validate_candidate_config(root, merge)
            with self.assertRaises(SystemExit):
                PREVIEW.validate_merge_tree(root, "0" * 40, head, merge, tree)
            with self.assertRaises(SystemExit):
                PREVIEW.validate_merge_tree(root, base, "0" * 40, merge, tree)
            with self.assertRaises(SystemExit):
                PREVIEW.validate_merge_tree(root, base, head, merge, "0" * 40)

        with tempfile.TemporaryDirectory() as temporary:
            root, base, head, merge, tree = self.make_merge_fixture(temporary, reverse_parents=True)
            with self.assertRaises(SystemExit):
                PREVIEW.validate_merge_tree(root, base, head, merge, tree)

        with tempfile.TemporaryDirectory() as temporary:
            root, base, head, merge, tree = self.make_merge_fixture(temporary, extra_path=True)
            with self.assertRaises(SystemExit):
                PREVIEW.validate_merge_tree(root, base, head, merge, tree)

        with tempfile.TemporaryDirectory() as temporary:
            root, base, head, merge, tree = self.make_merge_fixture(temporary, wrong_config=True)
            self.assertEqual(PREVIEW.validate_merge_tree(root, base, head, merge, tree), [PREVIEW.EFFECTIVE_CONFIG])
            with self.assertRaises(SystemExit):
                PREVIEW.validate_candidate_config(root, merge)

    def test_trusted_planner_selects_each_versioned_scenario_exactly(self):
        for scenario, expected in PREVIEW.SCENARIOS.items():
            with self.subTest(scenario=scenario):
                fields = PREVIEW.plan_scenario(ROOT, scenario)
                self.assertEqual(fields["selected_capabilities"], expected["capability"] or "required_gate_baseline")
                self.assertEqual(fields["run_required_gate_baseline"], "true")
                self.assertEqual(fields["run_rust_baseline"], "false")
                self.assertEqual(fields["needs_python"], "true")
                self.assertEqual(fields["needs_markdown"], "true")
                self.assertEqual(fields["needs_rust_toolchain"], "false")
                if expected["capability"] is None:
                    self.assertEqual(fields["scope"], "minimal")
                    for capability in ("doc_checker_contracts", "workflow_governance", "packaging_contracts", "operational_contracts"):
                        selector = "run_" + capability
                        if capability == "workflow_governance":
                            selector += "_contracts"
                        self.assertEqual(fields[selector], "false")
                    continue
                for capability in PREVIEW.SCENARIOS:
                    capability_name = PREVIEW.SCENARIOS[capability]["capability"]
                    if capability_name is None:
                        continue
                    selector = "run_" + capability_name
                    if capability == "workflow_governance":
                        selector += "_contracts"
                    self.assertEqual(fields[selector], "true" if capability == scenario else "false")

    def test_ordinary_document_pair_uses_trusted_legacy_and_versioned_configs(self):
        legacy = PREVIEW.plan_scenario(ROOT, "ordinary_document", mode="legacy")
        versioned = PREVIEW.plan_scenario(ROOT, "ordinary_document", mode="versioned")
        self.assertNotIn("execution_contract", legacy)
        self.assertEqual(legacy["planner_config_sha256"], "sha256:" + PREVIEW.EXPECTED_LEGACY_CONFIG_SHA256)
        self.assertEqual(versioned["execution_contract"], "required-domain-split/v1")
        self.assertEqual(versioned["planner_config_sha256"], "sha256:" + PREVIEW.EXPECTED_FIXTURE_SHA256)
        self.assertEqual(legacy["selected_capabilities"], "required_gate_baseline")
        self.assertEqual(versioned["selected_capabilities"], "required_gate_baseline")
        self.assertEqual(legacy["scope"], "minimal")
        self.assertEqual(versioned["scope"], "minimal")

    def test_legacy_plan_uses_pinned_fixture_when_effective_config_is_versioned(self):
        with tempfile.TemporaryDirectory() as temporary:
            root = Path(temporary)
            scripts = root / "scripts"
            scripts.mkdir()
            (scripts / "fixtures").mkdir()
            shutil.copy2(ROOT / "scripts/plan-rust-required-scope.py", scripts)
            shutil.copy2(ROOT / "scripts/ci-tests.sh", scripts)
            shutil.copy2(ROOT / PREVIEW.FIXTURE, scripts / "fixtures" / Path(PREVIEW.FIXTURE).name)
            shutil.copy2(ROOT / PREVIEW.LEGACY_FIXTURE, scripts / "fixtures" / Path(PREVIEW.LEGACY_FIXTURE).name)
            effective = scripts / Path(PREVIEW.EFFECTIVE_CONFIG).name
            shutil.copy2(ROOT / PREVIEW.FIXTURE, effective)

            legacy = PREVIEW.plan_scenario(root, "ordinary_document", mode="legacy")
            versioned = PREVIEW.plan_scenario(root, "ordinary_document", mode="versioned")

        self.assertEqual(
            hashlib.sha256((ROOT / PREVIEW.LEGACY_FIXTURE).read_bytes()).hexdigest(),
            PREVIEW.EXPECTED_LEGACY_CONFIG_SHA256,
        )
        self.assertNotIn("execution_contract", legacy)
        self.assertEqual(legacy["planner_config_sha256"], "sha256:" + PREVIEW.EXPECTED_LEGACY_CONFIG_SHA256)
        self.assertEqual(versioned["execution_contract"], "required-domain-split/v1")
        self.assertEqual(versioned["planner_config_sha256"], "sha256:" + PREVIEW.EXPECTED_FIXTURE_SHA256)

    def test_disposable_overlay_proves_one_changed_document_without_changing_candidate(self):
        candidate = subprocess.check_output(
            ["git", "-C", str(ROOT), "rev-parse", "HEAD^{commit}"], text=True
        ).strip()
        candidate_tree = subprocess.check_output(
            ["git", "-C", str(ROOT), "rev-parse", "HEAD^{tree}"], text=True
        ).strip()
        original_status = subprocess.check_output(
            ["git", "-C", str(ROOT), "status", "--porcelain"], text=True
        )
        overlay = None
        try:
            overlay, overlay_commit, overlay_tree = PREVIEW.create_document_overlay(ROOT, candidate)
            self.assertNotEqual(overlay_tree, candidate_tree)
            self.assertEqual(
                subprocess.check_output(
                    ["git", "-C", str(overlay), "rev-parse", "HEAD^1"], text=True
                ).strip(),
                candidate,
            )
            self.assertEqual(
                subprocess.check_output(
                    ["git", "-C", str(overlay), "diff", "--name-only", candidate, overlay_commit, "--", "doc/product"],
                    text=True,
                ).splitlines(),
                [PREVIEW.SCENARIOS["ordinary_document"]["path"]],
            )
            count, _elapsed = PREVIEW.verify_changed_range_document(
                ROOT, overlay, candidate, overlay_commit
            )
            self.assertEqual(count, 1)
        finally:
            if overlay is not None:
                PREVIEW.remove_document_overlay(ROOT, overlay)
        self.assertEqual(
            subprocess.check_output(["git", "-C", str(ROOT), "rev-parse", "HEAD^{tree}"], text=True).strip(),
            candidate_tree,
        )
        self.assertEqual(subprocess.check_output(["git", "-C", str(ROOT), "status", "--porcelain"], text=True), original_status)

    def test_dispatch_environment_never_enables_manual_only_selectors(self):
        fields = PREVIEW.plan_scenario(ROOT, "operational_contracts")
        context = self.context()
        sentinel_names = (
            "GH_TOKEN", "GITHUB_TOKEN", "ACTIONS_RUNTIME_TOKEN", "ACTIONS_ID_TOKEN_REQUEST_URL",
            "ACTIONS_ID_TOKEN_REQUEST_TOKEN", "GITHUB_OUTPUT", "GITHUB_ENV", "GITHUB_PATH",
            "GITHUB_STATE", "GITHUB_STEP_SUMMARY",
        )
        old_values = {
            name: os.environ.get(name)
            for name in (*sentinel_names, "PREVIEW_PYTHON", "OASIS7_CI_EXECUTION_CONTRACT", "OASIS7_CI_RUN_PACKAGING_CONTRACTS")
        }
        try:
            for name in sentinel_names:
                os.environ[name] = "must-not-reach-child"
            os.environ["OASIS7_CI_EXECUTION_CONTRACT"] = "stale-parent-value"
            os.environ["OASIS7_CI_RUN_PACKAGING_CONTRACTS"] = "true"
            os.environ["PREVIEW_PYTHON"] = "/tmp/preview-venv/bin/python"
            env = PREVIEW.dispatcher_environment(fields, context, "f" * 40)
        finally:
            for name, value in old_values.items():
                if value is None:
                    os.environ.pop(name, None)
                else:
                    os.environ[name] = value
        self.assertEqual(env["OASIS7_CI_RUN_HOSTED_ACCOUNT_SMOKE"], "false")
        self.assertEqual(env["OASIS7_CI_RUN_PROVIDER_LIVE_GATE"], "false")
        self.assertEqual(env["OASIS7_CI_RUN_OPERATIONAL_CONTRACTS"], "true")
        self.assertEqual(env["OASIS7_CI_EXECUTION_CONTRACT"], "required-domain-split/v1")
        for name in sentinel_names:
            self.assertNotIn(name, env)
        preview_bin = str(Path("/tmp/preview-venv/bin/python").resolve().parent)
        self.assertTrue(env["PATH"].startswith(preview_bin + os.pathsep))

    def test_legacy_dispatch_clears_inherited_versioned_environment_and_uses_overlay_head(self):
        fields = PREVIEW.plan_scenario(ROOT, "ordinary_document", mode="legacy")
        context = self.context()
        old_values = {
            name: os.environ.get(name)
            for name in (
                "PREVIEW_PYTHON", "OASIS7_CI_EXECUTION_CONTRACT",
                "OASIS7_CI_RUN_PACKAGING_CONTRACTS", "OASIS7_CI_NEEDS_MARKDOWN",
            )
        }
        try:
            os.environ["PREVIEW_PYTHON"] = "/tmp/preview-venv/bin/python"
            os.environ["OASIS7_CI_EXECUTION_CONTRACT"] = "stale-parent-value"
            os.environ["OASIS7_CI_RUN_PACKAGING_CONTRACTS"] = "true"
            os.environ["OASIS7_CI_NEEDS_MARKDOWN"] = "false"
            env = PREVIEW.dispatcher_environment(fields, context, "f" * 40, "c" * 40)
        finally:
            for name, value in old_values.items():
                if value is None:
                    os.environ.pop(name, None)
                else:
                    os.environ[name] = value
        self.assertNotIn("OASIS7_CI_EXECUTION_CONTRACT", env)
        self.assertNotIn("OASIS7_CI_RUN_PACKAGING_CONTRACTS", env)
        self.assertNotIn("OASIS7_CI_NEEDS_MARKDOWN", env)
        self.assertEqual(env["OASIS7_PRODUCT_DOC_BASE"], context["PREVIEW_BASE_SHA"])
        self.assertEqual(env["OASIS7_PRODUCT_DOC_HEAD"], "c" * 40)

    def test_timing_pair_runs_both_modes_against_the_same_overlay_even_if_first_fails(self):
        context = self.context()
        fields = {
            "legacy": {"planner_config_sha256": "legacy"},
            "versioned": {"planner_config_sha256": "versioned"},
        }
        order = ("legacy", "versioned")
        with mock.patch.object(PREVIEW, "run_child", side_effect=[(1, 2.5), (0, 3.5)]) as run_child:
            results = PREVIEW.run_document_timing_pair(
                ROOT, Path("/tmp/validated-overlay"), fields, context, "f" * 40, "c" * 40, order
            )
        self.assertEqual(results, {"legacy": (1, 2.5), "versioned": (0, 3.5)})
        self.assertEqual(run_child.call_count, 2)
        for call, mode in zip(run_child.call_args_list, order):
            args, kwargs = call
            self.assertEqual(args[0], ROOT)
            self.assertEqual(args[1], Path("/tmp/validated-overlay"))
            self.assertIs(args[2], fields[mode])
            self.assertEqual(args[4], "f" * 40)
            self.assertEqual(kwargs["product_head"], "c" * 40)
            self.assertEqual(kwargs["pair_leg"], mode)
        with self.assertRaises(SystemExit):
            PREVIEW.run_document_timing_pair(
                ROOT, Path("/tmp/validated-overlay"), fields, context, "f" * 40, "c" * 40, ("legacy", "legacy")
            )

    def test_validated_child_outputs_bind_tree_and_selected_capabilities(self):
        context = self.context()
        context["PREVIEW_SCENARIO"] = "packaging_contracts"
        fields = PREVIEW.plan_scenario(ROOT, context["PREVIEW_SCENARIO"])
        with tempfile.TemporaryDirectory() as temporary:
            output = Path(temporary) / "outputs.txt"
            PREVIEW.write_workflow_outputs(output, context, "f" * 40, fields)
            values = dict(line.split("=", 1) for line in output.read_text().splitlines())
        self.assertEqual(values["base_sha"], context["PREVIEW_BASE_SHA"])
        self.assertEqual(values["head_sha"], context["PREVIEW_HEAD_SHA"])
        self.assertEqual(values["tested_tree_sha"], context["PREVIEW_TESTED_TREE_SHA"])
        self.assertEqual(values["run_packaging_contracts"], "true")
        self.assertEqual(values["run_operational_contracts"], "false")

    def test_timing_pair_workflow_outputs_bind_overlay_and_both_results(self):
        context = self.context()
        context["PREVIEW_SCENARIO"] = "ordinary_document"
        fields = PREVIEW.plan_scenario(ROOT, "ordinary_document")
        extra = {
            "pair_order": "legacy;versioned",
            "legacy_run_result": "success",
            "legacy_elapsed_seconds": "12.345",
            "versioned_run_result": "success",
            "versioned_elapsed_seconds": "6.789",
            "document_overlay_parent_commit": "f" * 40,
            "document_overlay_commit": "c" * 40,
            "document_overlay_tree_sha": "d" * 40,
            "document_changed_path": PREVIEW.SCENARIOS["ordinary_document"]["path"],
            "document_changed_count": "1",
            "document_range_check_result": "success",
        }
        with tempfile.TemporaryDirectory() as temporary:
            output = Path(temporary) / "outputs.txt"
            PREVIEW.write_workflow_outputs(output, context, "f" * 40, fields, extra)
            values = dict(line.split("=", 1) for line in output.read_text().splitlines())
        self.assertEqual(values["preview_run_id"], context["PREVIEW_RUN_ID"])
        self.assertEqual(values["pair_order"], extra["pair_order"])
        self.assertEqual(values["document_overlay_parent_commit"], "f" * 40)
        self.assertEqual(values["legacy_run_result"], "success")
        self.assertEqual(values["versioned_run_result"], "success")

    def test_workflow_is_manual_unprivileged_and_non_required(self):
        workflow = (ROOT / ".github/workflows/required-gate-versioned-preview.yml").read_text()
        self.assertIn("workflow_dispatch:", workflow)
        self.assertNotRegex(workflow, r"(?m)^\s+(pull_request|pull_request_target|push|schedule):")
        self.assertIn("permissions: {}", workflow)
        self.assertNotIn("GITHUB_TOKEN", workflow)
        self.assertNotIn("secrets.", workflow)
        self.assertNotIn("upload-artifact", workflow)
        self.assertIn("refs/heads/main", workflow)
        self.assertIn("github.run_attempt == 1", workflow)
        self.assertIn("PREVIEW_RUN_ID: ${{ github.run_id }}", workflow)
        self.assertIn("tested_tree_sha", workflow)
        self.assertNotIn("required-gate:", workflow)

    def test_selected_hosted_child_jobs_capture_exact_run_attempt(self):
        workflow = (ROOT / ".github/workflows/required-gate-versioned-preview.yml").read_text()
        for job in (
            "preview-testnet-packages-macos-arm64-contract",
            "preview-windows-package-rollout-behavior",
            "preview-fleet-health-ubuntu",
            "preview-fleet-health-windows",
            "preview-fleet-health-macos",
        ):
            self.assertIn(job + ":", workflow)
        self.assertIn("needs.preview.outputs.run_packaging_contracts == 'true'", workflow)
        self.assertIn("needs.preview.outputs.run_operational_contracts == 'true'", workflow)
        self.assertIn("VALIDATED_MERGE_COMMIT", workflow)
        self.assertIn("VALIDATED_TREE_SHA", workflow)
        self.assertEqual(workflow.count('test "$tree" = "$VALIDATED_TREE_SHA"'), 5)
        self.assertIn("bash ./.preview-candidate/scripts/testnet-packages-macos-arm64-contract.test.sh", workflow)
        self.assertIn("bash ./.preview-candidate/scripts/p2p-public-testnet-package-rollout.test.sh", workflow)
        self.assertEqual(workflow.count("python ./.preview-candidate/scripts/p2p-public-testnet-fleet-health.test.py"), 3)
        self.assertIn("RUN_ID: ${{ github.run_id }}", workflow)
        self.assertIn("RUN_ATTEMPT: ${{ github.run_attempt }}", workflow)
        self.assertIn("FLEET_MACOS_RESULT: ${{ needs.preview-fleet-health-macos.result }}", workflow)
        self.assertIn("preview-outcome-summary:", workflow)
        self.assertIn("expect_child_result \"$PACKAGING_SELECTED\" \"$PACKAGE_RESULT\"", workflow)
        self.assertIn("expect_child_result \"$OPERATIONAL_SELECTED\" \"$FLEET_MACOS_RESULT\"", workflow)
        self.assertIn("Actual B-to-T diff: scripts/ci-required-scope.v2.json only", workflow)
        self.assertIn('[[ "$PREVIEW_RESULT" == success ]]', workflow)
        self.assertIn('[[ "$RUN_ATTEMPT" == 1 ]]', workflow)
        self.assertIn('[[ "$DOCUMENT_PATH" == doc/product/world-rules-core-gameplay/first-session-and-continuation.prd.md', workflow)
        self.assertIn('[[ "$LEGACY_RESULT" == success && "$VERSIONED_RESULT" == success ]]', workflow)
        self.assertIn('"pair_result={\'success\' if code == 0 else \'failure\'}"', DRIVER_PATH.read_text())
        self.assertIn("synthetic_changed_path=", DRIVER_PATH.read_text())
        self.assertIn("document_overlay_scope=temporary child commit of candidate T", DRIVER_PATH.read_text())
        self.assertNotIn("changed_range_document_validation=not_exercised_by_config_only_tree", DRIVER_PATH.read_text())

    def test_workflow_summary_accepts_complete_pair_and_rejects_missing_document_proof(self):
        workflow = (ROOT / ".github/workflows/required-gate-versioned-preview.yml").read_text()
        marker = "      - name: Record selected child outcomes and ordinary-document timing pair\n"
        section = workflow.split(marker, 1)[1]
        lines = section.splitlines()
        run_index = lines.index("        run: |\n".rstrip())
        body_lines = []
        for line in lines[run_index + 1 :]:
            if line.startswith("          "):
                body_lines.append(line[10:])
            elif not line.strip():
                body_lines.append("")
            else:
                break
        summary_script = textwrap.dedent("\n".join(body_lines))
        env = {
            "RUN_ID": "20260925001",
            "RUN_ATTEMPT": "1",
            "PREVIEW_RESULT": "success",
            "SCENARIO": "ordinary_document",
            "VALIDATED_RUN_ID": "20260925001",
            "BASE_SHA": "a" * 40,
            "HEAD_SHA": "b" * 40,
            "MERGE_COMMIT": "c" * 40,
            "TREE_SHA": "d" * 40,
            "PACKAGING_SELECTED": "false",
            "OPERATIONAL_SELECTED": "false",
            "PACKAGE_RESULT": "skipped",
            "WINDOWS_RESULT": "skipped",
            "FLEET_UBUNTU_RESULT": "skipped",
            "FLEET_WINDOWS_RESULT": "skipped",
            "FLEET_MACOS_RESULT": "skipped",
            "PAIR_ORDER": "legacy;versioned",
            "LEGACY_CONTRACT": "legacy",
            "VERSIONED_CONTRACT": "required-domain-split/v1",
            "LEGACY_CONFIG_SHA256": "sha256:" + PREVIEW.EXPECTED_LEGACY_CONFIG_SHA256,
            "VERSIONED_CONFIG_SHA256": "sha256:" + PREVIEW.EXPECTED_FIXTURE_SHA256,
            "LEGACY_CAPABILITIES": "required_gate_baseline",
            "VERSIONED_CAPABILITIES": "required_gate_baseline",
            "OVERLAY_PARENT": "c" * 40,
            "OVERLAY_COMMIT": "e" * 40,
            "OVERLAY_TREE": "f" * 40,
            "DOCUMENT_PATH": PREVIEW.SCENARIOS["ordinary_document"]["path"],
            "DOCUMENT_COUNT": "1",
            "DOCUMENT_CHECK_RESULT": "success",
            "DOCUMENT_CHECK_SECONDS": "1.234",
            "LEGACY_RESULT": "success",
            "LEGACY_SECONDS": "10.500",
            "VERSIONED_RESULT": "success",
            "VERSIONED_SECONDS": "6.250",
        }
        with tempfile.TemporaryDirectory() as temporary:
            summary_path = Path(temporary) / "summary.md"
            good_env = {**os.environ, **env, "GITHUB_STEP_SUMMARY": str(summary_path)}
            good = subprocess.run(
                ["bash", "-e", "-u", "-o", "pipefail", "-c", summary_script],
                env=good_env, text=True, capture_output=True,
            )
            self.assertEqual(good.returncode, 0, good.stderr)
            self.assertIn("Legacy timed child: success; 10.500s", summary_path.read_text())

            bad_env = {**good_env, "DOCUMENT_COUNT": "0"}
            bad = subprocess.run(
                ["bash", "-e", "-u", "-o", "pipefail", "-c", summary_script],
                env=bad_env, text=True, capture_output=True,
            )
            self.assertNotEqual(bad.returncode, 0)
            self.assertIn("changed-range proof is missing", bad.stderr)

    def test_driver_binds_pr_tree_to_base_head_and_trusted_policy(self):
        source = DRIVER_PATH.read_text()
        self.assertIn("read_public_pr(context)", source)
        self.assertIn("parents != [merge, base, head]", source)
        self.assertIn("PREVIEW_TESTED_TREE_SHA", source)
        self.assertIn("changed != [EFFECTIVE_CONFIG]", source)
        self.assertIn("candidate_bytes != fixture_bytes", source)
        self.assertIn("readiness_receipt=not-created", source)
        self.assertIn("required_gate_authority=unchanged", source)


if __name__ == "__main__":
    unittest.main(verbosity=2)
