//! Ordinary sidecar construction and default state.
use super::*;

impl RuntimeLlmSidecar {
    pub(in crate::viewer::runtime_live) fn new(decision_mode: ViewerLiveDecisionMode) -> Self {
        Self {
            decision_mode,
            prompt_profiles: BTreeMap::new(),
            prompt_profile_history: BTreeMap::new(),
            agent_player_bindings: BTreeMap::new(),
            player_agent_bindings: BTreeMap::new(),
            agent_public_key_bindings: BTreeMap::new(),
            player_auth_last_nonce: BTreeMap::new(),
            player_chat_intent_acks: BTreeMap::new(),
            primary_intents: BTreeMap::new(),
            llm_decision_mailbox: 0,
            runner: None,
            shadow_kernel: None,
            pending_actions: BTreeMap::new(),
            pending_provider_agent_chats: VecDeque::new(),
            provider_check_snapshot: None,
            hosted_service_phase: None,
            hosted_service_inflight: None,
            hosted_service_generation: 0,
            hosted_service_config_binding: None,
            #[cfg(any(test, feature = "test_tier_required"))]
            hosted_service_memory_failure: None,
            provider_metadata_generation: 0,
            provider_metadata_inflight: None,
            runtime_seed_locations: Vec::new(),
            runtime_seed_model: None,
            chunk_runtime: ChunkRuntimeConfig::default(),
            provider_session_ids: BTreeMap::new(),
            provider_agent_ids: BTreeSet::new(),
            hosted_local_mock_test_lane: false,
            #[cfg(any(test, feature = "test_tier_required"))]
            service_test_actor_agents: BTreeSet::new(),
            provider_context_seq: BTreeMap::new(),
            provider_contexts: BTreeMap::new(),
            provider_retry_contexts: BTreeMap::new(),
            provider_active_turns: BTreeMap::new(),
            provider_cognition_leases: BTreeMap::new(),
            provider_capability_identities: BTreeMap::new(),
            provider_continuation_proposals: BTreeMap::new(),
            provider_continuation_recovery_pending: BTreeMap::new(),
            provider_recovery_pending: BTreeMap::new(),
            provider_wake_recovery_pending: BTreeMap::new(),
            provider_service_pending: BTreeMap::new(),
            hosted_wait: None,
            hosted_restored_wait: None,
            hosted_restored_wait_decisions: BTreeMap::new(),
            hosted_resume: None,
            hosted_restored_resume: None,
            hosted_fresh_view_ready: false,
            hosted_admission: None,
            provider_restored_service_checkpoints: BTreeMap::new(),
            provider_scheduler_pending: BTreeMap::new(),
            provider_service_config: None,
            provider_service_query_state:
                crate::world_service::client::WorldServiceQueryState::default(),
            provider_service_required: false,
            provider_service_lineage_store_explicit: false,
            provider_service_projection: None,
            provider_service_signer: None,
            provider_wait_until: BTreeMap::new(),
            provider_feedback_seq: BTreeMap::new(),
            provider_feedback_seq_by_session: BTreeMap::new(),
            provider_memory_store: MemoryWriteStore::default(),
            provider_completed_decisions: VecDeque::new(),
            provider_stale_replans: BTreeMap::new(),
            provider_transport_exhausted: BTreeSet::new(),
            provider_terminal_states: BTreeMap::new(),
            provider_late_response_diagnostics: VecDeque::new(),
            provider_held_decisions: BTreeMap::new(),
            pending_provider_world_events: BTreeMap::new(),
            provider_world_event_quarantine: BTreeMap::new(),
            provider_lineage_store: None,
            provider_lineage_binding: None,
            provider_lineage_restored: false,
            provider_lineage_hydrated: false,
            provider_lineage_recovery_pending: None,
            pending_runtime_wakes: BTreeMap::new(),
        }
    }
}
