#!/usr/bin/env bash
set -euo pipefail

repo_root=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
cd "$repo_root"

usage() {
  cat <<'EOF'
Usage:
  ./scripts/p2p-build-governed-bootstrap-world.sh create \
    --genesis <path> \
    --out-dir <path> \
    [--world-scenario <scenario>] \
    [--merged-manifest-out <path>] \
    [--allow-overwrite]

  ./scripts/p2p-build-governed-bootstrap-world.sh validate \
    --world-dir <path> \
    --merged-public-manifest <path>

Description:
  Build a deterministic governed bootstrap world artifact for public_testnet.
  The generated world omits ephemeral distfs sidecar state so the artifact can
  be re-generated byte-for-byte from the same genesis/governance truth.
EOF
}

die() {
  printf 'error: %s\n' "$*" >&2
  exit 1
}

require_non_empty() {
  local flag=$1
  local value=$2
  [[ -n "$value" ]] || die "missing required option: $flag"
}

require_path() {
  local label=$1
  local path=$2
  [[ -e "$path" ]] || die "$label not found: $path"
}

mode=${1:-}
[[ -n "$mode" ]] || {
  usage >&2
  exit 2
}
shift || true

genesis_path=""
out_dir=""
merged_manifest_out=""
world_dir=""
merged_public_manifest=""
world_scenario=""
allow_overwrite=0

while [[ $# -gt 0 ]]; do
  case "$1" in
    --genesis)
      genesis_path=${2:-}
      shift 2
      ;;
    --out-dir)
      out_dir=${2:-}
      shift 2
      ;;
    --merged-manifest-out)
      merged_manifest_out=${2:-}
      shift 2
      ;;
    --world-scenario)
      world_scenario=${2:-}
      shift 2
      ;;
    --world-dir)
      world_dir=${2:-}
      shift 2
      ;;
    --merged-public-manifest)
      merged_public_manifest=${2:-}
      shift 2
      ;;
    --allow-overwrite)
      allow_overwrite=1
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      die "unknown option: $1"
      ;;
  esac
done

resolve_repo_path() {
  python3 - "$repo_root" "$1" <<'PY'
import pathlib
import sys

repo_root = pathlib.Path(sys.argv[1]).resolve()
raw = pathlib.Path(sys.argv[2]).expanduser()
if raw.is_absolute():
    print(raw.resolve())
else:
    print((repo_root / raw).resolve())
PY
}

merge_manifest_from_genesis() {
  local genesis_abs=$1
  local merged_manifest_abs=$2

  python3 - "$genesis_abs" "$merged_manifest_abs" <<'PY'
import json
import pathlib
import sys

genesis_path = pathlib.Path(sys.argv[1]).resolve()
merged_out = pathlib.Path(sys.argv[2]).resolve()

with genesis_path.open("r", encoding="utf-8") as fh:
    genesis = json.load(fh)

refs = genesis.get("governance_bootstrap_refs", {})
gov_ref = refs.get("governance_public_manifest_ref")
registry_ref = refs.get("genesis_validator_registry_ref")
if not gov_ref:
    raise SystemExit("genesis missing governance_bootstrap_refs.governance_public_manifest_ref")
if not registry_ref:
    raise SystemExit("genesis missing governance_bootstrap_refs.genesis_validator_registry_ref")

def resolve_ref(raw: str) -> pathlib.Path:
    candidate = pathlib.Path(raw).expanduser()
    if candidate.is_absolute():
        return candidate.resolve()
    for base in (genesis_path.parent, *genesis_path.parents):
        resolved = (base / candidate).resolve()
        if resolved.exists():
            return resolved
    return (genesis_path.parent / candidate).resolve()

governance_manifest_path = resolve_ref(gov_ref)
validator_registry_path = resolve_ref(registry_ref)

with governance_manifest_path.open("r", encoding="utf-8") as fh:
    governance_manifest_raw = json.load(fh)
with validator_registry_path.open("r", encoding="utf-8") as fh:
    validator_registry = json.load(fh)

if isinstance(governance_manifest_raw, list):
    governance_manifest = governance_manifest_raw
elif isinstance(governance_manifest_raw, dict) and isinstance(governance_manifest_raw.get("entries"), list):
    governance_manifest = governance_manifest_raw["entries"]
else:
    raise SystemExit(f"governance manifest must be a list or bundle-with-entries: {governance_manifest_path}")
if not isinstance(validator_registry, dict):
    raise SystemExit(f"validator registry must be an object: {validator_registry_path}")

slot_id = validator_registry.get("slot_id")
threshold = validator_registry.get("threshold")
validators = validator_registry.get("validators", [])
if not slot_id:
    raise SystemExit(f"validator registry missing slot_id: {validator_registry_path}")
if threshold is None:
    raise SystemExit(f"validator registry missing threshold: {validator_registry_path}")

merged = [
    entry
    for entry in governance_manifest
    if entry.get("slot_id") != slot_id
]
for validator in validators:
    merged.append(
        {
            "slot_id": slot_id,
            "signer_id": validator["node_id"],
            "node_id": validator["node_id"],
            "scheme": validator["scheme"],
            "threshold": threshold,
            "public_key_hex": validator["finality_signer_public_key"],
            "stake": validator["stake"],
        }
    )

merged_out.parent.mkdir(parents=True, exist_ok=True)
with merged_out.open("w", encoding="utf-8") as fh:
    json.dump(merged, fh, ensure_ascii=True, indent=2)
    fh.write("\n")
PY
}

canonicalize_world() {
  local source_world_dir=$1
  local target_world_dir=$2

  rm -rf "$target_world_dir"
  mkdir -p "$target_world_dir"
  cp "$source_world_dir/snapshot.json" "$target_world_dir/snapshot.json"
  cp "$source_world_dir/journal.json" "$target_world_dir/journal.json"
  cp "$source_world_dir/journal.segments.json" "$target_world_dir/journal.segments.json"
  cp "$source_world_dir/snapshot.manifest.json" "$target_world_dir/snapshot.manifest.json"

  python3 - "$source_world_dir/module_registry.json" "$target_world_dir/module_registry.json" <<'PY'
import json
import pathlib
import sys

src = pathlib.Path(sys.argv[1]).resolve()
dst = pathlib.Path(sys.argv[2]).resolve()

with src.open("r", encoding="utf-8") as fh:
    payload = json.load(fh)

payload["updated_at"] = 0
with dst.open("w", encoding="utf-8") as fh:
    json.dump(payload, fh, ensure_ascii=True, indent=2)
    fh.write("\n")
PY
}

validate_generated_world_artifact() {
  local world_dir_abs=$1
  local provenance_abs=$2
  local merged_public_manifest_abs=$3

  python3 - "$world_dir_abs" "$provenance_abs" "$merged_public_manifest_abs" <<'PY'
import hashlib
import json
import pathlib
import sys

world_dir = pathlib.Path(sys.argv[1]).resolve()
provenance_path = pathlib.Path(sys.argv[2]).resolve()
merged_public_manifest_path = pathlib.Path(sys.argv[3]).resolve()
snapshot_path = world_dir / "snapshot.json"
journal_path = world_dir / "journal.json"

for path in (snapshot_path, journal_path, provenance_path, merged_public_manifest_path):
    if not path.is_file():
        raise SystemExit(f"generated world artifact missing required file: {path}")

with provenance_path.open("r", encoding="utf-8") as fh:
    provenance = json.load(fh)
if provenance.get("artifact_kind") != "simulator_world_generation":
    raise SystemExit(f"generated world provenance has unexpected artifact_kind: {provenance_path}")
if not provenance.get("scenario_id"):
    raise SystemExit(f"generated world provenance missing scenario_id: {provenance_path}")
if not isinstance(provenance.get("seed"), int) or provenance["seed"] <= 0:
    raise SystemExit(f"generated world provenance seed must be positive: {provenance_path}")
config = provenance.get("config")
if not isinstance(config, dict) or not config:
    raise SystemExit(f"generated world provenance config must be a non-empty object: {provenance_path}")

manifest_bytes = merged_public_manifest_path.read_bytes()
actual_manifest_sha256 = hashlib.sha256(manifest_bytes).hexdigest()
if provenance.get("public_manifest_sha256") != actual_manifest_sha256:
    raise SystemExit(
        f"generated world provenance public_manifest_sha256 mismatch: {provenance_path}"
    )
try:
    public_manifest = json.loads(manifest_bytes)
except json.JSONDecodeError as exc:
    raise SystemExit(f"generated world public manifest is invalid json: {merged_public_manifest_path}: {exc}") from exc
if not isinstance(public_manifest, list) or not public_manifest:
    raise SystemExit(f"generated world public manifest must be a non-empty array: {merged_public_manifest_path}")
if provenance.get("public_manifest_entry_count") != len(public_manifest):
    raise SystemExit(
        f"generated world provenance public_manifest_entry_count mismatch: {provenance_path}"
    )

with snapshot_path.open("r", encoding="utf-8") as fh:
    snapshot = json.load(fh)
locations = snapshot.get("model", {}).get("locations")
if not isinstance(locations, dict) or not locations:
    raise SystemExit(f"generated world snapshot has no model.locations: {snapshot_path}")

with journal_path.open("r", encoding="utf-8") as fh:
    journal = json.load(fh)
events = journal.get("events")
if not isinstance(events, list):
    raise SystemExit(f"generated world journal events must be a list: {journal_path}")
if not any(event.get("kind", {}).get("type") == "ChunkGenerated" for event in events if isinstance(event, dict)):
    raise SystemExit(f"generated world journal has no ChunkGenerated event: {journal_path}")
PY
}

case "$mode" in
  create)
    require_non_empty "--genesis" "$genesis_path"
    require_non_empty "--out-dir" "$out_dir"
    genesis_path=$(resolve_repo_path "$genesis_path")
    out_dir=$(resolve_repo_path "$out_dir")
    require_path "--genesis" "$genesis_path"

    if [[ -z "$merged_manifest_out" ]]; then
      merged_manifest_out="$out_dir/merged-public-manifest-entries.json"
    fi
    merged_manifest_out=$(resolve_repo_path "$merged_manifest_out")

    if [[ -e "$out_dir" && "$allow_overwrite" -ne 1 ]]; then
      die "output directory already exists; pass --allow-overwrite: $out_dir"
    fi

    mkdir -p "$repo_root/.tmp"
    tmp_root=$(mktemp -d "$repo_root/.tmp/governed-bootstrap-world-build.XXXXXX")
    trap 'rm -rf "$tmp_root"' EXIT
    tmp_world_dir="$tmp_root/world"
    tmp_merged_manifest="$tmp_root/merged-public-manifest-entries.json"

    merge_manifest_from_genesis "$genesis_path" "$tmp_merged_manifest"
    ./scripts/cargo-dev.sh run -p oasis7 --bin oasis7_governance_registry_import -- \
      --world-dir "$tmp_world_dir" \
      --public-manifest "$tmp_merged_manifest"
    ./scripts/cargo-dev.sh run -p oasis7 --bin oasis7_governance_registry_audit -- \
      --world-dir "$tmp_world_dir" \
      --public-manifest "$tmp_merged_manifest" \
      --strict-manifest-match

    rm -rf "$out_dir"
    mkdir -p "$out_dir"
    canonicalize_world "$tmp_world_dir" "$out_dir/world"
    if [[ -n "$world_scenario" ]]; then
      ./scripts/cargo-dev.sh run -p oasis7 --bin oasis7_generate_world_artifact -- \
        --scenario "$world_scenario" \
        --world-dir "$out_dir/generated-scenario-world" \
        --provenance-out "$out_dir/world-generation-provenance.json" \
        --public-manifest "$tmp_merged_manifest"
    fi
    cp "$tmp_merged_manifest" "$merged_manifest_out"

    printf '%s\n' "$out_dir"
    ;;
  validate)
    require_non_empty "--world-dir" "$world_dir"
    require_non_empty "--merged-public-manifest" "$merged_public_manifest"
    world_dir=$(resolve_repo_path "$world_dir")
    merged_public_manifest=$(resolve_repo_path "$merged_public_manifest")
    require_path "--world-dir" "$world_dir"
    require_path "--merged-public-manifest" "$merged_public_manifest"
    [[ ! -e "$world_dir/.distfs-state" ]] || die "world artifact must not include .distfs-state: $world_dir/.distfs-state"
    [[ ! -e "$world_dir/distfs.recovery.audit.json" ]] || die "world artifact must not include distfs.recovery.audit.json"
    python3 - "$world_dir/module_registry.json" <<'PY'
import json
import pathlib
import sys

path = pathlib.Path(sys.argv[1]).resolve()
with path.open("r", encoding="utf-8") as fh:
    payload = json.load(fh)
updated_at = payload.get("updated_at")
if updated_at != 0:
    raise SystemExit(f"module_registry.updated_at must be 0 for canonical artifact, got {updated_at}")
PY
    ./scripts/cargo-dev.sh run -p oasis7 --bin oasis7_governance_registry_audit -- \
      --world-dir "$world_dir" \
      --public-manifest "$merged_public_manifest" \
      --strict-manifest-match
    generated_root="$(dirname "$world_dir")"
    generated_provenance="$generated_root/world-generation-provenance.json"
    generated_world_dir="$generated_root/generated-scenario-world"
    if [[ -f "$generated_provenance" ]]; then
      validate_generated_world_artifact "$generated_world_dir" "$generated_provenance" "$merged_public_manifest"
    fi
    ;;
  *)
    usage >&2
    exit 2
    ;;
esac
