export function createGovernanceVoteQuoteIntegration({ buildAuthEnvelope, clone, ensureHostedPlayerAuthAvailable, ensureRegisteredPlayerSession, getSocket, nextAuthNonce, sendJson, signAuthPayload, state }) {
  const requestKey = (proposal, option, weight) => `${proposal}|${option}|${weight}`;
  async function requestGovernanceVoteQuote(proposalKey, option, weight) {
    const proposal = String(proposalKey || "").trim(); const choice = String(option || "").trim(); const voteWeight = Number(weight);
    if (!proposal || !choice || !Number.isSafeInteger(voteWeight) || voteWeight < 1) return { ok: false, reason: "governance quote requires a proposal, option, and positive vote weight" };
    if (state.governanceVoteQuoteRequest?.status === "pending") return { ok: false, reason: "governance quote request is already pending" };
    const socket = getSocket(); if (!socket || socket.readyState !== WebSocket.OPEN) return { ok: false, reason: "governance quote requires a connected viewer websocket" };
    try { await ensureHostedPlayerAuthAvailable(); const auth = state.auth; const agent = String(auth.boundAgentId || "").trim(); if (!auth.available || !agent) return { ok: false, reason: "governance quote requires an active bound player session" }; await ensureRegisteredPlayerSession(agent); const request = { proposal_key: proposal, option: choice, weight: voteWeight, player_id: auth.playerId, public_key: auth.publicKey }; const nonce = nextAuthNonce(); const payload = buildAuthEnvelope({ operation: "gameplay_action", action_id: "quote_governance_vote", target_agent_id: `proposal_key:${proposal}|option:${choice}|weight:${voteWeight}`, player_id: auth.playerId, public_key: auth.publicKey, nonce }); request.auth = { scheme: "ed25519", player_id: auth.playerId, public_key: auth.publicKey, nonce, signature: await signAuthPayload(payload, auth) }; state.governanceVoteQuote = null; state.governanceVoteQuoteRequest = { status: "pending", error: null, requestKey: requestKey(proposal, choice, voteWeight) }; sendJson({ type: "quote_governance_vote", request }); return { ok: true, request: clone(request) }; } catch (error) { const reason = String(error); state.governanceVoteQuoteRequest = { status: "error", error: reason }; return { ok: false, reason }; }
  }
  function handleGovernanceVoteQuote(quote) { const pending = state.governanceVoteQuoteRequest; if (!quote || typeof quote !== "object" || pending?.status !== "pending") return false; state.governanceVoteQuote = clone(quote); state.governanceVoteQuoteRequest = { status: "received", error: null }; return true; }
  function handleGovernanceVoteQuoteError(error) { if (String(error?.action_id || "") !== "quote_governance_vote" || state.governanceVoteQuoteRequest?.status !== "pending") return false; state.governanceVoteQuoteRequest = { status: "error", error: String(error?.code || error?.message || "governance quote failed") }; return true; }
  function invalidateGovernanceVoteQuote() { state.governanceVoteQuote = null; state.governanceVoteQuoteRequest = { status: "idle", error: null }; }
  return { requestGovernanceVoteQuote, handleGovernanceVoteQuote, handleGovernanceVoteQuoteError, invalidateGovernanceVoteQuote };
}
