import { createSignal } from "solid-js";

const value = (item) => item == null || item === "" ? "—" : String(item);
const Metric = (props) => <div class="metric"><div class="metric__label">{props.label}</div><div class="metric__value">{props.value}</div></div>;

export function GovernanceVoteQuoteCard(props) {
  const q = () => props.quote || {};
  return <section class="panel panel--nested" data-testid="governance-vote-quote" data-quote-kind="preflight" data-submission-allowed="false"><div class="panel__header"><div class="stack stack--compact"><div class="panel__eyebrow">{props.tr(props.locale, "提交前预览", "Before You Commit")}</div><div class="panel__title">{props.tr(props.locale, "治理投票结果预览", "Governance Vote Outcome")}</div><div class="panel__meta-copy">{props.tr(props.locale, "这是签名的只读预览；不会投票、改票或推进世界时间。", "This is a signed read-only quote. It does not cast or change a vote, or advance world time.")}</div></div></div><div class="panel__body stack"><div class="summary-grid"><Metric label={props.tr(props.locale, "提案", "Proposal")} value={value(q().proposal_topic)} /><Metric label={props.tr(props.locale, "剩余时间", "Time left")} value={`${value(q().ticks_remaining)} ${props.tr(props.locale, "步", "ticks")}`} /><Metric label={props.tr(props.locale, "当前 / 所需法定人数", "Current / required quorum")} value={`${value(q().current_quorum_weight)} / ${value(q().required_quorum_weight)}`} /><Metric label={props.tr(props.locale, "当前 / 所需支持", "Current / required support")} value={`${value(q().current_pass_bps)} / ${value(q().required_pass_bps)} bps`} /><Metric label={props.tr(props.locale, "我的票权 / 改变潜力", "My vote / swing potential")} value={`${value(q().actor_vote_weight)} / ${value(q().vote_swing_potential)}`} /><Metric label={props.tr(props.locale, "行动后结果", "Outcome after action")} value={value(q().likely_outcome_after_action)} /></div><div class="feedback-summary">{`${props.tr(props.locale, "通过后改变", "Change if passed")}: ${value(q().world_change_if_passed)}`}</div><div class="feedback-summary feedback-summary--warn">{`${props.tr(props.locale, "失败或过期代价", "Failure or expiry cost")}: ${value(q().cost_or_cooldown_if_failed)}`}</div><div class="feedback-summary">{`${props.tr(props.locale, "建议", "Recommended")}: ${value(q().recommended_governance_action)} — ${value(q().why_this_vote_matters)}`}</div></div></section>;
}

export function GovernanceVoteQuotePanel(props) {
  const [proposal, setProposal] = createSignal(""); const [option, setOption] = createSignal("approve"); const [weight, setWeight] = createSignal("1"); const [localError, setLocalError] = createSignal(""); const remote = () => props.requestState || {}; const error = () => localError() || (remote().status === "error" ? remote().error : "");
  async function request(event) { event.preventDefault(); setLocalError(""); const result = await props.requestGovernanceVoteQuote(proposal(), option(), weight()); if (!result?.ok) setLocalError(result?.reason || "quote failed"); }
  return <section class="panel panel--nested" data-testid="governance-vote-quote-panel"><div class="panel__header"><div class="stack stack--compact"><div class="panel__title">{props.tr(props.locale, "治理投票结果预览", "Governance Vote Outcome")}</div></div></div><div class="panel__body stack"><form class="stack stack--compact" onSubmit={request}><label><span>{props.tr(props.locale, "提案 ID", "Proposal ID")}</span><input value={proposal()} onInput={(event) => setProposal(event.currentTarget.value)} /></label><label><span>{props.tr(props.locale, "选项", "Option")}</span><input value={option()} onInput={(event) => setOption(event.currentTarget.value)} /></label><label><span>{props.tr(props.locale, "票权", "Vote weight")}</span><input type="number" min="1" value={weight()} onInput={(event) => setWeight(event.currentTarget.value)} /></label><button class="button button--secondary" type="submit" disabled={remote().status === "pending"}>{props.tr(props.locale, "请求投票预览", "Request vote outcome")}</button></form>{error() ? <div role="alert" class="feedback-summary feedback-summary--warn">{props.tr(props.locale, "无法获取治理投票预览。", "Could not get the governance vote quote.")}</div> : null}{props.quote && remote().status !== "pending" ? <GovernanceVoteQuoteCard quote={props.quote} locale={props.locale} tr={props.tr} /> : null}</div></section>;
}
