export function createMarketQuoteDecisionIntegration({ buildAuthEnvelope, clone, ensureHostedPlayerAuthAvailable, ensureRegisteredPlayerSession, getSocket, nextAuthNonce, sendJson, signAuthPayload, state }) {
  async function requestMarketQuoteDecision(consume) {
    const normalized = Array.isArray(consume) ? consume.map((item) => ({ material: String(item?.material || "").trim(), amount: Number(item?.amount) })) : [];
    if (!normalized.length || normalized.some((item) => !item.material || !Number.isSafeInteger(item.amount) || item.amount <= 0)) return { ok: false, reason: "market preview requires named materials and positive whole-number amounts" };
    const socket = getSocket(); if (!socket || socket.readyState !== WebSocket.OPEN) return { ok: false, reason: "market preview requires a connected viewer websocket" };
    try { await ensureHostedPlayerAuthAvailable(); const auth = state.auth; const agent = String(auth.boundAgentId || "").trim(); if (!auth.available || !agent) return { ok: false, reason: "market preview requires an active bound player session" }; await ensureRegisteredPlayerSession(agent); const request = { consume: normalized, player_id: auth.playerId, public_key: auth.publicKey }; const nonce = nextAuthNonce(); const payload = buildAuthEnvelope({ operation: "gameplay_action", action_id: "quote_market_decision", target_agent_id: `market_consume:${JSON.stringify(normalized)}`, player_id: auth.playerId, public_key: auth.publicKey, nonce }); request.auth = { scheme: "ed25519", player_id: auth.playerId, public_key: auth.publicKey, nonce, signature: await signAuthPayload(payload, auth) }; state.marketQuoteDecision = null; state.marketQuoteDecisionRequest = { status: "pending", error: null }; sendJson({ type: "quote_market_decision", request }); return { ok: true, request: clone(request) }; } catch (error) { const reason = String(error); state.marketQuoteDecisionRequest = { status: "error", error: reason }; return { ok: false, reason }; }
  }
  function handleMarketQuoteDecision(quote) { if (!quote || typeof quote !== "object") return false; state.marketQuoteDecision = clone(quote); state.marketQuoteDecisionRequest = { status: "received", error: null }; return true; }
  function handleMarketQuoteDecisionError(error) { if (String(error?.action_id || "") !== "quote_market_decision") return false; state.marketQuoteDecisionRequest = { status: "error", error: String(error?.message || "market preview failed") }; return true; }
  function injectMarketQuoteDecisionForTest(quote) { return handleMarketQuoteDecision(quote); }
  return { requestMarketQuoteDecision, handleMarketQuoteDecision, handleMarketQuoteDecisionError, injectMarketQuoteDecisionForTest };
}
