import { createSignal } from "solid-js";

function display(value) { return value == null || value === "" ? "—" : String(value); }
function powerState(value, locale, tr) { return ({ normal: tr(locale, "正常", "Normal"), low_power: tr(locale, "低电量", "Low power"), critical: tr(locale, "临界电量", "Critical power"), shutdown: tr(locale, "已停机", "Shutdown") })[String(value || "")] || tr(locale, "状态暂不可用", "State unavailable"); }
function affordability(value, locale, tr) { return ({ healthy: tr(locale, "下一步可负担", "Next action affordable"), limited: tr(locale, "下一步受限", "Next action limited"), blocked: tr(locale, "下一步不可负担", "Next action blocked") })[String(value || "")] || tr(locale, "可负担性暂不可用", "Affordability unavailable"); }
function recommendation(value, locale, tr) { return ({ proceed_sale: tr(locale, "可谨慎继续出售", "Proceed with this sale cautiously"), reduce_sale: tr(locale, "减少出售量后重新预估", "Reduce the sale, then request a fresh quote"), defer_sale: tr(locale, "暂缓本次出售", "Defer this sale") })[String(value || "")] || tr(locale, "重新请求预估后再决定", "Request a fresh quote before deciding"); }
function rationale(quote, locale, tr) {
  if (quote.production_interrupt_risk) return tr(locale, "出售后电力余量可能中断生产；请优先保护可行动时长。", "This sale can interrupt production after it reduces power; protect your action runway first.");
  return tr(locale, "运行时未标记生产中断风险；世界状态变化后请重新请求预估。", "The runtime did not flag production interruption risk; request a fresh quote after world state changes.");
}
function Metric(props) { return <div class="metric"><div class="metric__label">{props.label}</div><div class="metric__value">{props.value}</div></div>; }

export function PowerSaleQuoteCard(props) {
  const quote = () => props.quote || {}; const locale = () => props.locale; const tr = props.tr;
  return <section class="panel panel--nested" data-testid="power-sale-quote" data-quote-kind="preflight" data-seller-agent-id={display(quote().seller_agent_id)} data-buyer-agent-id={display(quote().buyer_agent_id)} data-amount={display(quote().sale_amount)} data-requested-price-per-pu={display(quote().price_per_pu)}>
    <div class="panel__header"><div class="stack stack--compact"><div class="panel__eyebrow">{tr(locale(), "提交前估价", "Before You Commit")}</div><div class="panel__title">{tr(locale(), "电力出售预估", "Power Sale Quote")}</div><div class="panel__meta-copy">{tr(locale(), "这是已签名的只读预估，不会出售电力、收取收入、推进时间或保证稍后成交。", "This is a signed read-only quote. It does not sell power, collect revenue, advance time, or guarantee a later sale.")}</div></div></div>
    <div class="panel__body stack"><div class="badge-row"><span class="badge badge--accent">{tr(locale(), "预估", "quote")}</span><span class="badge">{`${tr(locale(), "买方", "Buyer")}: ${display(quote().buyer_agent_id)}`}</span><span class="badge">{`${tr(locale(), "出售量", "Sale amount")}: ${display(quote().sale_amount)}`}</span><span class="badge">{`${tr(locale(), "单价", "Price per unit")}: ${display(quote().price_per_pu)}`}</span></div>
      <div class="summary-grid"><Metric label={tr(locale(), "当前电力", "Current power")} value={display(quote().current_power_level)} /><Metric label={tr(locale(), "预计收入", "Expected revenue")} value={display(quote().expected_revenue)} /><Metric label={tr(locale(), "出售后电力状态", "Power state after sale")} value={`${powerState(quote().power_state_before, locale(), tr)} → ${powerState(quote().power_state_after_sale, locale(), tr)}`} /><Metric label={tr(locale(), "剩余可行动时长", "Remaining runway")} value={`${display(quote().remaining_runway_ticks)} ${tr(locale(), "步", "ticks")}`} /><Metric label={tr(locale(), "下一步可负担性", "Next-action affordability")} value={affordability(quote().next_action_affordability_after_sale, locale(), tr)} /></div>
      <div class={quote().production_interrupt_risk ? "feedback-summary feedback-summary--warn" : "feedback-summary"} data-testid="power-sale-production-risk">{quote().production_interrupt_risk ? tr(locale(), "生产中断风险：本次出售可能中断生产。", "Production interruption risk: this sale can interrupt production.") : tr(locale(), "生产中断风险：运行时未标记本次出售会中断生产。", "Production interruption risk: the runtime did not flag this sale as interrupting production.")}</div>
      <div class="feedback-summary" data-testid="power-sale-rationale">{rationale(quote(), locale(), tr)}</div><div class="feedback-summary" data-testid="power-sale-recommendation">{`${tr(locale(), "建议", "Recommended")}: ${recommendation(quote().recommended_sale_action, locale(), tr)}`}</div>
    </div>
  </section>;
}

export function PowerSaleQuotePanel(props) {
  const [buyer, setBuyer] = createSignal("agent-buyer"); const [amount, setAmount] = createSignal("10"); const [price, setPrice] = createSignal("0"); const [requesting, setRequesting] = createSignal(false); const [localError, setLocalError] = createSignal("");
  const locale = () => props.locale; const tr = props.tr; const remote = () => props.requestState || {};
  const stale = () => Boolean(props.quote) && (String(props.quote.buyer_agent_id) !== buyer().trim() || String(props.quote.sale_amount) !== amount().trim() || String(props.quote.price_per_pu) !== price().trim());
  async function requestQuote(event) { event.preventDefault(); setLocalError(""); setRequesting(true); try { const result = await props.requestPowerSaleQuote(buyer(), amount(), price()); if (!result?.ok) setLocalError(result?.reason || "quote failed"); } catch (error) { setLocalError(String(error)); } finally { setRequesting(false); } }
  return <section id="viewer-power-sale-quote-panel" class="panel panel--nested" data-testid="power-sale-quote-panel" data-quote-kind="preflight"><div class="panel__header"><div class="stack stack--compact"><div class="panel__eyebrow">{tr(locale(), "出售前估价", "Before Selling")}</div><div class="panel__title">{tr(locale(), "先查看电力出售影响", "Preview Power Sale Impact")}</div></div></div><div class="panel__body stack"><form class="stack stack--compact" data-testid="power-sale-quote-request-form" onSubmit={requestQuote}><label><span>{tr(locale(), "买方 Agent", "Buyer Agent")}</span><input aria-label={tr(locale(), "买方 Agent", "Buyer Agent")} value={buyer()} onInput={(event) => setBuyer(event.currentTarget.value)} /></label><label><span>{tr(locale(), "出售电量", "Power amount")}</span><input aria-label={tr(locale(), "出售电量", "Power amount")} type="number" min="1" step="1" inputmode="numeric" value={amount()} onInput={(event) => setAmount(event.currentTarget.value)} /></label><label><span>{tr(locale(), "每单位报价", "Price per unit")}</span><input aria-label={tr(locale(), "每单位报价", "Price per unit")} type="number" min="0" step="1" inputmode="numeric" value={price()} onInput={(event) => setPrice(event.currentTarget.value)} /></label><button type="submit" class="button button--secondary" disabled={requesting() || remote().status === "pending"}>{requesting() || remote().status === "pending" ? tr(locale(), "正在请求预估…", "Requesting quote…") : tr(locale(), "请求出售预估", "Request sale quote")}</button></form>{localError() || remote().status === "error" ? <div class="feedback-summary feedback-summary--error" role="alert">{tr(locale(), "无法获取出售预估。请检查连接、玩家会话和输入后重试。", "Could not get the sale quote. Check the connection, player session, and inputs, then retry.")}</div> : null}{remote().status === "received" && !stale() ? <div class="feedback-summary" role="status">{tr(locale(), "预估已返回；这不会保证稍后出售成功。", "Quote received; it does not guarantee a later sale succeeds.")}</div> : null}{stale() && remote().status !== "pending" ? <div class="feedback-summary feedback-summary--warn" role="status">{tr(locale(), "输入已变更；当前预估已过期。请重新请求预估后再出售。", "Inputs changed; this quote is stale. Request a new quote before selling.")}</div> : null}{remote().status === "pending" ? <div class="feedback-summary" role="status">{tr(locale(), "正在刷新预估；旧预估已失效。", "Refreshing the quote; the previous quote is no longer current.")}</div> : null}{props.quote && remote().status !== "pending" ? <PowerSaleQuoteCard quote={props.quote} locale={locale()} tr={tr} /> : null}</div></section>;
}
