import { createSignal } from "solid-js";

function display(value) { return value == null || value === "" ? "—" : String(value); }
function riskCopy(value, locale, tr) { return ({ normal: tr(locale, "电力风险正常", "Normal power risk"), critical: tr(locale, "临界电力风险", "Critical power risk"), shutdown: tr(locale, "停机风险", "Shutdown risk") })[String(value || "")] || tr(locale, "电力风险待确认", "Power risk pending"); }
function warningRisk(value) { return ["critical", "shutdown"].includes(String(value || "")); }
function preStepCopy(value, locale, tr) { return ({ schedule_now: tr(locale, "可安排生产", "Schedule production now"), restore_power: tr(locale, "先恢复电力，再安排生产", "Restore power before scheduling production") })[String(value || "")] || tr(locale, "重新请求预估后再决定", "Request a fresh quote before deciding"); }
function shortageCopy(quote, locale, tr) { const delay = Number(quote.local_shortage_delay_ticks || 0); return delay > 0 ? tr(locale, `本地短缺：${delay} 步（${display(quote.shortage_reason)}）`, `Local shortage: ${delay} ticks (${display(quote.shortage_reason)})`) : tr(locale, "本地短缺：无", "Local shortage: none"); }
function Metric(props) { return <div class="metric"><div class="metric__label">{props.label}</div><div class="metric__value">{props.value}</div></div>; }

export function ScheduleRecipeQuoteCard(props) {
  const quote = () => props.quote || {}; const locale = () => props.locale; const tr = props.tr;
  return <section class="panel panel--nested" data-testid="schedule-recipe-quote" data-quote-kind="preflight">
    <div class="panel__header"><div class="stack stack--compact"><div class="panel__eyebrow">{tr(locale(), "提交前估价", "Before You Commit")}</div><div class="panel__title">{tr(locale(), "配方排产预估", "Schedule Recipe Quote")}</div><div class="panel__meta-copy">{tr(locale(), "这是只读预估，不会安排生产、扣除资源、推进时间或生成回执。", "This is a read-only quote. It does not schedule production, spend resources, advance time, or create a receipt.")}</div></div></div>
    <div class="panel__body stack"><div class="badge-row"><span class="badge badge--accent">{tr(locale(), "预估", "quote")}</span><span class="badge">{`${tr(locale(), "工厂", "Factory")}: ${display(quote().factory_id)}`}</span><span class="badge">{`${tr(locale(), "配方", "Recipe")}: ${display(quote().recipe_id)}`}</span><span class="badge">{`${tr(locale(), "批次", "Batches")}: ${display(quote().batches)}`}</span></div>
      <div class={warningRisk(quote().continue_production_risk) ? "feedback-summary feedback-summary--warn" : "feedback-summary"} data-testid="schedule-recipe-quote-risk">{`${tr(locale(), "风险", "Risk")}: ${riskCopy(quote().continue_production_risk, locale(), tr)}`}</div><div class={warningRisk(quote().continue_production_risk) ? "feedback-summary feedback-summary--warn" : "feedback-summary"} data-testid="schedule-recipe-quote-recommendation">{`${tr(locale(), "建议", "Recommended")}: ${preStepCopy(quote().recommended_pre_step, locale(), tr)}`}</div>
      <div class="summary-grid"><Metric label={tr(locale(), "基础时长", "Base duration")} value={`${display(quote().base_duration_ticks)} ${tr(locale(), "步", "ticks")}`} /><Metric label={tr(locale(), "本地短缺", "Local shortage")} value={`${display(quote().local_shortage_delay_ticks)} ${tr(locale(), "步", "ticks")}`} /><Metric label={tr(locale(), "成品", "Finished product")} value={`${display(quote().finished_product_id)} × ${display(quote().finished_product_units)}`} /><Metric label={tr(locale(), "电力成本", "Electricity cost")} value={display(quote().electricity_cost)} /><Metric label={tr(locale(), "排产后电力", "Electricity after scheduling")} value={display(quote().electricity_after)} /><Metric label={tr(locale(), "电池续航", "Battery runway")} value={`${display(quote().runway_before_ticks)} → ${display(quote().runway_after_ticks)} ${tr(locale(), "步", "ticks")}`} /></div>
      <div class="feedback-summary">{shortageCopy(quote(), locale(), tr)}</div><div class="feedback-summary">{tr(locale(), "维护：本次预估未跟踪维护压力。", "Maintenance: not tracked for this quote.")}</div>
    </div>
  </section>;
}

export function ScheduleRecipeQuotePanel(props) {
  const [factory, setFactory] = createSignal("factory-0"); const [recipe, setRecipe] = createSignal("assemble_hardware"); const [batches, setBatches] = createSignal("1"); const [requesting, setRequesting] = createSignal(false); const [localError, setLocalError] = createSignal(""); const locale = () => props.locale; const tr = props.tr; const remote = () => props.requestState || {};
  const error = () => remote().status === "error" || localError() ? tr(locale(), "无法获取排产预估。请检查连接、玩家会话和输入后重试。", "Could not get the schedule quote. Check the connection, player session, and inputs, then retry.") : "";
  async function requestQuote(event) { event.preventDefault(); setLocalError(""); setRequesting(true); try { const result = await props.requestScheduleRecipeQuote(factory(), recipe(), batches()); if (!result?.ok) setLocalError(result?.reason || "quote failed"); } catch (requestError) { setLocalError(String(requestError)); } finally { setRequesting(false); } }
  return <section id="viewer-schedule-recipe-quote-panel" class="panel panel--nested" data-testid="schedule-recipe-quote-panel" data-quote-kind="preflight"><div class="panel__header"><div class="stack stack--compact"><div class="panel__eyebrow">{tr(locale(), "提交前估价", "Before You Commit")}</div><div class="panel__title">{tr(locale(), "配方排产预估", "Schedule Recipe Quote")}</div></div></div><div class="panel__body stack"><form class="stack stack--compact" data-testid="schedule-recipe-quote-request-form" onSubmit={requestQuote}><label><span>{tr(locale(), "工厂", "Factory")}</span><input aria-label={tr(locale(), "工厂", "Factory")} value={factory()} onInput={(event) => setFactory(event.currentTarget.value)} /></label><label><span>{tr(locale(), "配方", "Recipe")}</span><input aria-label={tr(locale(), "配方", "Recipe")} value={recipe()} onInput={(event) => setRecipe(event.currentTarget.value)} /></label><label><span>{tr(locale(), "批次", "Batches")}</span><input aria-label={tr(locale(), "批次", "Batches")} type="number" min="1" step="1" inputmode="numeric" value={batches()} onInput={(event) => setBatches(event.currentTarget.value)} /></label><button type="submit" class="button button--secondary" disabled={requesting() || remote().status === "pending"}>{requesting() || remote().status === "pending" ? tr(locale(), "正在请求预估…", "Requesting quote…") : tr(locale(), "请求排产预估", "Request schedule quote")}</button></form>{error() ? <div class="feedback-summary feedback-summary--error" role="alert">{error()}</div> : null}{remote().status === "pending" ? <div class="feedback-summary" role="status">{tr(locale(), "正在请求预估…", "Requesting quote…")}</div> : null}{remote().status === "received" ? <div class="feedback-summary" role="status">{tr(locale(), "预估已返回；安排前请查看风险。", "Quote received; review the risk before scheduling.")}</div> : null}{props.quote && remote().status !== "pending" ? <ScheduleRecipeQuoteCard quote={props.quote} locale={locale()} tr={tr} /> : null}</div></section>;
}
