export function createWarDeclarationQuoteIntegration({ buildAuthEnvelope, clone, ensureHostedPlayerAuthAvailable, ensureRegisteredPlayerSession, getSocket, nextAuthNonce, sendJson, signAuthPayload, state }) {
  async function requestWarDeclarationQuote(aggressorAllianceId, defenderAllianceId, intensity) {
    const aggressor = String(aggressorAllianceId || "").trim(); const defender = String(defenderAllianceId || "").trim(); const strength = Number(intensity);
    if (!aggressor || !defender || aggressor === defender || !Number.isSafeInteger(strength) || strength < 1 || strength > 10) return { ok: false, reason: "war quote requires two different alliances and an intensity from 1 to 10" };
    const socket = getSocket(); if (!socket || socket.readyState !== WebSocket.OPEN) return { ok: false, reason: "war quote requires a connected viewer websocket" };
    try { await ensureHostedPlayerAuthAvailable(); const auth = state.auth; const agent = String(auth.boundAgentId || "").trim(); if (!auth.available || !agent) return { ok: false, reason: "war quote requires an active bound player session" }; await ensureRegisteredPlayerSession(agent); const request = { aggressor_alliance_id: aggressor, defender_alliance_id: defender, intensity: strength, player_id: auth.playerId, public_key: auth.publicKey }; const nonce = nextAuthNonce(); const payload = buildAuthEnvelope({ operation: "gameplay_action", action_id: "quote_declare_war", target_agent_id: `aggressor_alliance_id:${aggressor}|defender_alliance_id:${defender}|intensity:${strength}`, player_id: auth.playerId, public_key: auth.publicKey, nonce }); request.auth = { scheme: "ed25519", player_id: auth.playerId, public_key: auth.publicKey, nonce, signature: await signAuthPayload(payload, auth) }; state.warDeclarationQuote = null; state.warDeclarationQuoteRequest = { status: "pending", error: null }; sendJson({ type: "quote_declare_war", request }); return { ok: true, request: clone(request) }; } catch (error) { const reason = String(error); state.warDeclarationQuoteRequest = { status: "error", error: reason }; return { ok: false, reason }; }
  }
  function handleWarDeclarationQuote(quote) { if (!quote || typeof quote !== "object" || state.warDeclarationQuoteRequest?.status !== "pending") return false; state.warDeclarationQuote = clone(quote); state.warDeclarationQuoteRequest = { status: "received", error: null }; return true; }
  function handleWarDeclarationQuoteError(error) { if (String(error?.action_id || "") !== "quote_declare_war") return false; state.warDeclarationQuoteRequest = { status: "error", error: String(error?.code || error?.message || "war quote failed") }; return true; }
  function invalidateWarDeclarationQuote() { state.warDeclarationQuote = null; state.warDeclarationQuoteRequest = { status: "idle", error: null }; }
  function injectWarDeclarationQuoteForTest(quote) { state.warDeclarationQuote = clone(quote); state.warDeclarationQuoteRequest = { status: "received", error: null }; return clone(quote); }
  return { requestWarDeclarationQuote, handleWarDeclarationQuote, handleWarDeclarationQuoteError, invalidateWarDeclarationQuote, injectWarDeclarationQuoteForTest };
}
