import { createSignal } from "solid-js";
import { buildWarDeclarationQuoteDisplayModel } from "./war_declaration_quote_display_model.js";

const display = (value) => value == null || value === "" ? "—" : String(value);
const Metric = (props) => <div class="metric"><div class="metric__label">{props.label}</div><div class="metric__value">{props.value}</div></div>;
const mobilization = (required, current, after, locale, tr) => `${tr(locale, "需求", "Required")} ${display(required)} · ${tr(locale, "当前", "Current")} ${display(current)} · ${tr(locale, "提交后", "After submission")} ${display(after)}`;

export function WarDeclarationQuoteCard(props) {
  const q = () => props.quote || {};
  const view = () => buildWarDeclarationQuoteDisplayModel(q(), props.locale, props.tr);
  return <section class="panel panel--nested" id="war-quote-card" data-testid="war-declaration-quote" data-quote-kind="preflight" data-quote-fingerprint={display(q().state_fingerprint)} data-state-fingerprint={display(q().state_fingerprint)} data-submission-allowed="false">
    <div class="panel__header"><div class="panel__eyebrow">{props.tr(props.locale, "提交前估价", "Before You Commit")}</div><div class="panel__title">{props.tr(props.locale, "战争结果预估", "War Outcome Quote")}</div><div class="panel__meta-copy">{props.tr(props.locale, "这是已签名的只读预估；不会宣战、预留资源、推进时间或创建战争。", "This is a signed read-only quote. It does not declare war, reserve resources, advance time, or create a conflict.")}</div></div>
    <div class="panel__body stack">
      <div id="war-quote-status" class={q().mobilization_affordable ? "feedback-summary" : "feedback-summary feedback-summary--warn"} role="status">{`${props.tr(props.locale, "状态", "Status")}: ${view().settlementPath} · ${view().affordability}`}</div>
      <div id="war-quote-blocker" class={q().conflict_status === "none" ? "feedback-summary" : "feedback-summary feedback-summary--warn"} data-testid="war-declaration-blocker">{`${props.tr(props.locale, "冲突窗口", "Conflict window")}: ${view().conflictStatus} · ${props.tr(props.locale, "可于", "Retry at")} ${display(q().conflict_window_blocked_until)} ${props.tr(props.locale, "步", "ticks")}`}</div>
      <div class="summary-grid"><Metric label={props.tr(props.locale, "双方联盟", "Alliances")} value={`${display(q().actor_alliance_id)} → ${display(q().target_alliance_id)}`} /><Metric label={props.tr(props.locale, "最小胜利强度", "Minimum winning intensity")} value={display(q().minimum_winning_intensity)} /><Metric label={props.tr(props.locale, "预计胜负", "Projected outcome")} value={view().projectedOutcome} /><Metric label={props.tr(props.locale, "预计持续", "Projected duration")} value={`${display(q().war_duration_ticks)} ${props.tr(props.locale, "步", "ticks")}`} /><Metric label={props.tr(props.locale, "攻击 / 防守评分", "Aggressor / defender score")} value={`${display(q().aggressor_score_estimate)} → ${display(q().defender_score_estimate)}`} /><Metric label={props.tr(props.locale, "胜负差", "Projected margin")} value={display(q().victory_margin_estimate)} /></div>
      <div class="feedback-summary" data-testid="war-declaration-mobilization-electricity">{`${props.tr(props.locale, "动员电力", "Mobilization electricity")}: ${mobilization(q().mobilization_electricity_required, q().mobilization_electricity_current, q().mobilization_electricity_after, props.locale, props.tr)}`}</div>
      <div class="feedback-summary" data-testid="war-declaration-mobilization-data">{`${props.tr(props.locale, "动员数据", "Mobilization data")}: ${mobilization(q().mobilization_data_required, q().mobilization_data_current, q().mobilization_data_after, props.locale, props.tr)}`}</div>
      <div id="war-quote-risk" class="feedback-summary feedback-summary--warn" data-testid="war-declaration-risk">{`${props.tr(props.locale, "风险", "Risk")}: ${view().risk}`}</div>
      <div id="war-quote-recommendation" class="feedback-summary" data-testid="war-declaration-recommendation">{`${props.tr(props.locale, "建议", "Recommended")}: ${view().recommendedAction}`}</div>
      <div class="feedback-detail">{`${props.tr(props.locale, "替代路线", "Alternative")}: ${view().alternativeAction}`}</div>
      <button id="war-quote-declare" class="button button--secondary" type="button" disabled data-testid="war-declaration-submit-disabled">{props.tr(props.locale, "宣战提交尚不可用", "War declaration submission unavailable")}</button>
    </div>
  </section>;
}

export function WarDeclarationQuotePanel(props) {
  const [a, setA] = createSignal("alliance.red"); const [d, setD] = createSignal("alliance.blue"); const [i, setI] = createSignal("3"); const [busy, setBusy] = createSignal(false); const [localError, setLocalError] = createSignal("");
  const remote = () => props.requestState || {};
  const stale = () => props.quote && (String(props.quote.actor_alliance_id) !== a().trim() || String(props.quote.target_alliance_id) !== d().trim() || String(props.quote.intensity) !== i().trim() || Number(props.quote.quoted_at_tick) !== Number(props.logicalTime));
  async function request(event) { event.preventDefault(); setLocalError(""); setBusy(true); try { const result = await props.requestWarDeclarationQuote(a(), d(), i()); if (!result?.ok) setLocalError(result?.reason || "quote failed"); } catch (error) { setLocalError(String(error)); } finally { setBusy(false); } }
  const error = () => localError() || remote().status === "error" ? String(localError() || remote().error || "") : "";
  return <section class="panel panel--nested" id="war-declaration-quote-panel" data-testid="war-declaration-quote-panel"><div class="panel__header"><div class="panel__title">{props.tr(props.locale, "战争结果预估", "War Outcome Quote")}</div></div><div class="panel__body stack"><form class="stack stack--compact" data-testid="war-declaration-quote-request-form" onSubmit={request}><label><span>{props.tr(props.locale, "进攻联盟", "Aggressor alliance")}</span><input aria-label={props.tr(props.locale, "进攻联盟", "Aggressor alliance")} value={a()} onInput={(e) => setA(e.currentTarget.value)} /></label><label><span>{props.tr(props.locale, "防守联盟", "Defender alliance")}</span><input aria-label={props.tr(props.locale, "防守联盟", "Defender alliance")} value={d()} onInput={(e) => setD(e.currentTarget.value)} /></label><label><span>{props.tr(props.locale, "强度", "Intensity")}</span><input aria-label={props.tr(props.locale, "强度", "Intensity")} type="number" min="1" max="10" value={i()} onInput={(e) => setI(e.currentTarget.value)} /></label><button id="war-quote-refresh" class="button button--secondary" type="submit" disabled={busy() || remote().status === "pending"}>{stale() ? props.tr(props.locale, "刷新战争预估", "Refresh war quote") : props.tr(props.locale, "请求战争预估", "Request war quote")}</button></form>{error() ? <div id="war-quote-unavailable" role="alert" class="feedback-summary feedback-summary--warn" data-testid="war-declaration-unavailable">{error().includes("unavailable") ? props.tr(props.locale, "当前结算路径未提供权威只读预估。", "The current settlement path has no authoritative read-only quote.") : props.tr(props.locale, "无法获取战争预估。", "Could not get the war quote.")}</div> : null}{stale() ? <div id="war-quote-stale" role="status" class="feedback-summary feedback-summary--warn" data-testid="war-declaration-quote-stale">{props.tr(props.locale, "世界状态或输入已变化；当前预估已过期。请刷新预估。", "World state or inputs changed; this quote is stale. Refresh the quote.")}</div> : null}{props.quote && remote().status !== "pending" ? <WarDeclarationQuoteCard quote={props.quote} locale={props.locale} tr={props.tr} /> : null}</div></section>;
}
